### ISSUE TITLE
iOS peripheral disconnects after 30 seconds

### ISSUE THREAD

**Issue by cristianmjg** [Adam-Langley/pybleno#10]
Hi, 

I have a Raspberry Pi sending an integer to an iOS utilizing the CoreBluetooth framework. After 30 seconds, the iOS app disconnects from the peripheral (RPi). I wrote one service with one characteristic with the 'notify' property and uses onSubscription to actually send the data. In the body of onSubscription I use time.sleep() to control the frequency of data sending. When there is no delay, the peripheral on iOS disconnects almost immediately, when there is a 30ms delay, communication lasts about 30 seconds. Are there BLE protocols/rules/specifications that specify the frequency I'm talking about? Is there any way to set these parameters through pybleno or any way of implementing them? Any input would be truly helpful!

Below is the characteristic:

from pybleno import *

import time
import array

class PredictionCharacteristic(Characteristic):

  def __init__(self, predict):
    Characteristic.__init__(self, {
      'uuid': '16dedcf4027f435fb1e622e601276950',
      'properties': ['notify'],
      'descriptors': [
        Descriptor(
          value = 'Sends over a value from 0-9 after gesture-making.'
          )],
      'value': None
    })
    
    self.predict = predict
    self._value = None
    self.updateValueCallback = None
    
  def onSubscribe(self, maxValueSize, updateValueCallback):
    print ('TranslatorCharacteristic: onSusbcribe')
    
    
    # finger_sensor = list()
    # test_build_mapping()
    d = self.predict.build_mapping()
    # Define delay between readings
    delay = 1

    while True:
      flex_data = 0
      # Read the flex sensor data, A0 is thumb, A4 is pinky
      for i in range(0, 5):
        flex_level = self.predict.ReadChannel(i)
        flex_data += int(flex_level > 800) * pow(10, i)
        # print("flex sensor {}: ADC = {}".format(i, flex_level))

      p = self.predict.predict(flex_data, d)
      print(p)
      if p is None:
        print 'we are handling None'
      	p = 16

      updateValueCallback(array.array('B', [p]))
      time.sleep(0.02)

  def onUnsubscribe(self):
    print ('TranslatorCharacteristic: onUnsubscribe')
    self._updateValueCallBack = None

**Comment by Adam-Langley** [comment]
Hi @cristianmjg 
I would be concerned about the fact you're blocking the subscription. You should return from any reads, writes, and subscribes as quickly as possible.
What you're probably seeing is the iOS device is dropping the connection because the subscribe does not return in a timely manner.

What you want to do here, is spawn a thread on the subscribe, so that the subscribe can return immediately. Then you can use the thread to push intermittent notifications out to the subscriber as often as you like.

I do something similar, and my notifications keep coming in for hours at 1 second intervals.

**Comment by Adam-Langley** [comment]
Please reopen if required.
