### ISSUE TITLE
Pizza Example does not work

### ISSUE THREAD

**Issue by johanneskpp** [Adam-Langley/pybleno#21]
The Pizza-Example does not start advertising. The node version works fine but I need it for python.
Hope you can help me!

**Comment by johanneskpp** [comment]
![unbenannt](https://user-images.githubusercontent.com/37586219/47365199-552d1580-d6db-11e8-9416-8b930e8c68e2.PNG)

**Comment by ecasadod** [comment]
Hello,

I've been facing the same problem. If you put Bleno initialization (`bleno = Bleno()`) AFTER Pizza Service init, it will work. 

Best regards,

Enrique

**Comment by Adam-Langley** [comment]
This issue arises from the inherence threading model difference between Python, and Nodejs from which this library was ported.
In Node, the main event loop pauses until the the of the initialization process. In Python, the initialization (and hence the 'power on' event) is performed as soon as the Bleno() object is created.
I have updated the API to now require the use of bleno.Start() - this gives the opportunity to register your callbacks before the subsystem is started.

Remember to update your code to use bleno.Start()! See the updated examples.

Thanks.

Fixed by fa245fa1b1701af682c8880f60a41795d4ce9700
